# Representations and metrics

# Question 1

<img src="images/Screen Shot 2016-07-02 at 9.34.11 AM.png">

*Screenshot taken from [Coursera](https://www.coursera.org/learn/ml-clustering-and-retrieval/exam/YV0W4/representations-and-metrics)*

<!--TEASER_END-->

**Answer**
- https://www.coursera.org/learn/ml-clustering-and-retrieval/discussions/weeks/2/threads/yoIkdz9XEeaQYwrcKTQWAQ
- The coordinate differences get squared before scaling, so the amount of variations gets squared too

In [13]:
def calculate_weight(feature):
    weight = (1/(max(feature) - min(feature))) ** 2
    return weight

price = calculate_weight(np.array([500000, 350000, 600000, 400000],  dtype=float))
room = calculate_weight(np.array([3, 2, 4, 2],  dtype=float))
lot = calculate_weight(np.array([1840, 1600, 2000, 1900],  dtype=float))

print price
print room
print lot

1.6e-11
0.25
6.25e-06


# Question 2

<img src="images/Screen Shot 2016-07-02 at 9.39.55 AM.png">

*Screenshot taken from [Coursera](https://www.coursera.org/learn/ml-clustering-and-retrieval/exam/YV0W4/representations-and-metrics)*

<!--TEASER_END-->

**Answer**
- Word counts
    - Sentence 1: [2, 1, 1, 1, 1, 1, 1, 1, 0]
    - Sentence 2: [0, 2, 1, 1, 0, 1, 0, 1, 2]
- Euclidean distance:

In [16]:
import numpy as np

s1 = np.array([2, 1, 1, 1, 1, 1, 1, 1, 0, 0], dtype=float)
s2 = np.array([0, 2, 1, 1, 0, 0, 0, 1, 2, 1], dtype=float)
print s1
print s2

euclidean_distance = np.sqrt(np.sum((s1 - s2)**2))
euclidean_distance

[ 2.  1.  1.  1.  1.  1.  1.  1.  0.  0.]
[ 0.  2.  1.  1.  0.  0.  0.  1.  2.  1.]


3.6055512754639891

# Question 3

<img src="images/Screen Shot 2016-07-02 at 9.39.59 AM.png">

*Screenshot taken from [Coursera](https://www.coursera.org/learn/ml-clustering-and-retrieval/exam/YV0W4/representations-and-metrics)*

<!--TEASER_END-->

In [17]:
import numpy as np

s1 = np.array([2, 1, 1, 1, 1, 1, 1, 1, 0, 0], dtype=float)
s2 = np.array([0, 2, 1, 1, 0, 0, 0, 1, 2, 1], dtype=float)
print s1
print s2
cosine_similarity = np.dot(s1, s2)/(np.sqrt(np.sum(s1**2)) * np.sqrt(np.sum(s2**2)))
cosine_distance = 1 - cosine_similarity
cosine_distance

[ 2.  1.  1.  1.  1.  1.  1.  1.  0.  0.]
[ 0.  2.  1.  1.  0.  0.  0.  1.  2.  1.]


0.5648058601107554

# Question 4

<img src="images/Screen Shot 2016-07-02 at 9.23.00 AM.png">

*Screenshot taken from [Coursera](https://www.coursera.org/learn/ml-clustering-and-retrieval/exam/YV0W4/representations-and-metrics)*

<!--TEASER_END-->

# Question 5

<img src="images/Screen Shot 2016-07-02 at 9.40.07 AM.png">

*Screenshot taken from [Coursera](https://www.coursera.org/learn/ml-clustering-and-retrieval/exam/YV0W4/representations-and-metrics)*

<!--TEASER_END-->

**Answer**
- Given the number of documents, $tf*idf$ = 0, so idf = 0

$$idf = \large log \frac{\text{# docs}}{\text{1 + # docs}} = 0$$
$$\large \frac{\text{# docs}}{\text{1 + # docs}} = e^0 = 1$$


# Question 6

<img src="images/Screen Shot 2016-07-02 at 9.40.22 AM.png">

*Screenshot taken from [Coursera](https://www.coursera.org/learn/ml-clustering-and-retrieval/exam/YV0W4/representations-and-metrics)*

<!--TEASER_END-->